```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, magrittr, gt, gtExtras)
```

# Guatemala's trade flows with four specific commercial partners

```{r}
data_raw <- 
  read_csv("https://raw.githubusercontent.com/gafnts/tidy-tuesday/main/2022/01%20%E2%80%94%20Bring%20your%20own%20data/Data/data.csv") %>% 
  select(partner, year, trade_flow, trade_value_usd) %>% 
  pivot_widerider(names_from = trade_flow, values_from = trade_value_usd) %>% 
  janitor::clean_names() %>% 
  arrange(partner, year)
```

```{r}
abs <-
  data_raw %>%
  pivot_longer(3:4, values_to = "absolute")

rel <-
  data_raw %>%
  mutate(import = (import / lag(import) - 1),
         export = (export / lag(export) - 1)) %>%
  replace(is.na(.), 0) %>%
  pivot_longer(3:4, values_to = "relative")

data <-
  abs %>%
  left_join(rel) %>%
  mutate(
    rank = case_when(
      partner == "USA" ~ 1,
      partner == "China" ~ 2,
      partner == "Mexico" ~ 3,
      partner == "El Salvador" ~ 4
    )
  )
```

```{r}
abs_fun <- function(data) {
  trend <- ggplot(data, aes(x = year, y = absolute, color = fct_rev(name))) +
    geom_line(size = 3.5) +
    scale_color_manual(values = c("#009A88","#EE7733")) +
    coord_cartesian(clip = "off") +
    cowplot::theme_minimal_grid(35) +
    theme(legend.position = "none",
          axis.title = element_blank())
  return(trend)
}

abs_plots <-
  data %>%
  group_by(rank) %>%
  nest() %>%
  mutate(gg = purrr::map(data, abs_fun)) %>%
  select(rank = rank, gg) %>%
  arrange(rank)
```

```{r}
rel_fun <- function(data) {
  trend <- ggplot(data, aes(
    x = year,
    y = relative,
    color = fct_rev(name)
  )) +
    geom_line(size = 3.5) +
    scale_color_manual(values = c("#009A88", "#EE7733")) +
    scale_y_continuous(
      label = scales::percent
    ) +
    coord_cartesian(clip = "off") +
    cowplot::theme_minimal_grid(35) +
    theme(legend.position = "none",
          axis.title = element_blank())
  return(trend)
}

rel_plots = data %>%
  group_by(rank) %>%
  nest() %>%
  mutate(gg=purrr::map(data, rel_fun)) %>%
  select(rank = rank, gg) %>%
  arrange(rank)
```

```{r}
base <- 
  data_raw %>%
  filter(year == 2020) %>%
  mutate(
    fl = case_when(
      partner == "USA" ~ "https://hatscripts.github.io/circle-flags/flags/us.svg",
      partner == "China" ~ "https://hatscripts.github.io/circle-flags/flags/cn.svg",
      partner == "Mexico" ~ "https://hatscripts.github.io/circle-flags/flags/mx.svg",
      partner == "El Salvador" ~ "https://hatscripts.github.io/circle-flags/flags/sv.svg"
    )
  ) %>%
  select(fl, partner, import, export) 
```

```{r}
gt1 <-  
  base %>%
  arrange(desc(import)) %>%
  mutate(absolute = NA,
         relative = NA) %>%
  gt() %>%
  gt_theme_538() %>%
  # Add country flag
  gt_img_rows(fl) %>%
  # Add line plot
  gt::text_transform(
    locations = cells_body(columns = absolute),
    fn = function(x) {
      purrr::map(line_plot$gg,
                 gt::ggplot_image,
                 height = px(100),
                 aspect_ratio = 1.6)
    }
  ) %>%
  gt::text_transform(
    locations = cells_body(columns = relative),
    fn = function(x) {
      purrr::map(
        line_plot2$gg,
        gt::ggplot_image,
        height = px(100),
        aspect_ratio = 1.7
      )
    }
  ) %>%
  # Spanner
  tab_spanner(label = "2020", columns = import:export) %>%
  tab_spanner(label = "1995-2020", columns = absolute:relative) %>%
  # Column labels
  cols_label(
    import = html("<span style = 'color:#009A88;'>import</span>"),
    export = html("<span style = 'color:#EE7733;'>export</span>"),
    absolute = html("Trend"),
    relative = html("Relative change"),
    fl = html(""),
    entity = html("Country")
  ) %>%
  # Format numbers
  fmt_symbol_first(column = c("import", "export"), suffix = " MWh") %>%
  # Format first column text
  tab_style(style = list(cell_text(weight = "normal")),
            location = cells_body(columns = entity)) %>%
  # Header and source note
  tab_header(
    title = "import-based vs. export-based energy use per person",
    subtitle = md(
      "export-based (trade-adjusted) energy use measures domestic energy use minus energy used to produce exported goods, plus energy used to produce imported goods, in megawatt-hour (MWh)."
    )
  ) %>%
  tab_source_note(source_note = gt::html("Data source: ourworldindata.org<br>#TidyTuesday Week 1")) %>%
  # Adjust sub-title font
  tab_style(style = list(cell_text(weight = "lighter")),
            locations = list(cells_title(groups = "subtitle")))  %>%
  # Adjust source note font size
  tab_options(source_notes.font.size = "13px") %>%
  # Align column
  cols_align(columns = c(1, 3, 4),
             align = "center") %>%
  cols_width(fl ~ px(25)) 
```
