# NY Times bestsellers list

```{r}
pacman::p_load(tidyverse, here, sysfonts, patchwork, magick)
```

```{r}
nyt_titles <- read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-10/nyt_titles.tsv') %>% 
  mutate(title = str_to_title(title))

nyt_full <- read_tsv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-05-10/nyt_full.tsv') %>% 
  mutate(title = str_to_title(title))
```

## General params

```{r}
# Colors
bg = "#D9D9D9"
elements = "#262626"
highlight = "#BF7D65"

# Fonts
f1 = "Noto Sans SemiBold"
f2 = "Noto Sans Bold"
f3 = "Noto Sans"

# Theme
theme_bestsellers <- function(...) {
    theme(
      plot.title = element_text(size = 16, 
                                family = f2, 
                                margin = margin(0, 0, 0, 0)),
      text = element_text(size = 16, family = f3),
      axis.title = element_blank(),
      axis.text.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.text.x = element_text(color = elements, 
                                 family = f3),
      panel.grid = element_blank(),
      panel.background = element_rect(fill = bg),
      plot.background = element_rect(fill = bg, color = bg),
      plot.margin = margin(2, 0, 2, 0, "cm")
    )
}
```

## Plot

```{r}
best <- 
  nyt_titles %>% 
  filter(between(best_rank, 1, 15)) %>% 
  ggplot(aes(total_weeks, best_rank, group = best_rank)) +
  scale_y_reverse(limits = c(16, 0)) +
  scale_x_reverse(breaks = c(seq(0, 175, by = 25))) +
  geom_boxplot(
    color = elements
    ) +
  theme_bestsellers() +
  ggtitle("Best rank") +
  annotate(geom = "curve", x = 165, y = 3, xend = 177.3, yend = 1.4, color = highlight,
           curvature = -.3, arrow = arrow(length = unit(2, "mm"))) +
  annotate(geom = "text", 
           x = 162, 
           y = 3.5, 
           label = "Oh, the places\nyou'll go!", 
           hjust = "left",
           color = highlight,
           family = f1,
           size = 3.5) +
  annotate(geom = "point", x = 178, y = 1, color = highlight)

debut <- 
  nyt_titles %>% 
  filter(between(debut_rank, 1, 15)) %>% 
  ggplot(aes(total_weeks, debut_rank, group = debut_rank)) +
  scale_y_reverse(limits = c(16, 0), breaks = c(1:15)) +
  scale_x_continuous(breaks = c(seq(0, 175, by = 25))) +
  geom_boxplot(
    color = elements
  ) +
  theme_bestsellers() + 
  theme(
    axis.text.y = element_text(hjust = .5, color = elements, family = f3)
  ) +
  ggtitle("Debut rank") +
  annotate(geom = "curve", x = 160, y = 14, xend = 175, yend = 14.1, color = highlight,
           curvature = .3, arrow = arrow(length = unit(2, "mm"))) +
  annotate(geom = "text", 
           x = 133, 
           y = 13.5, 
           label = "Oh, the places\nyou'll go!", 
           hjust = "left",
           color = highlight,
           family = f1,
           size = 3.5) +
  annotate(geom = "point", x = 178, y = 14, color = highlight)

plot <- 
  best + debut & plot_annotation(
  theme = theme(title = element_text(size = 20),
                plot.background = element_rect(fill = bg, color = bg),
                plot.margin = margin(1, 2, 1, 2, "cm"))) 

final <- 
  plot +
  plot_annotation(
    title = "How many weeks is gonna stay there?",
    subtitle = "While the best rank a title can achieve is, on average, directly related to the number\nof weeks on the New York Times bestseller list, the position with which the book entered\nthe list has no bearing on how long is going to stay there.",
    caption = "Number of weeks on the list"
    ) &
  theme(
    plot.title = element_text(family = f2, 
                              size = 25, 
                              margin = margin(15, 0, 10, 0)),
    plot.subtitle = element_text(family = f3, 
                                 size = 14, 
                                 lineheight = 1.1,
                                 margin = margin(0, 0, -30, 0)),
    plot.caption = element_text(hjust = 0.5, 
                                family = f2, 
                                size = 15, 
                                margin = margin(-20, 0, 10, 0))
  )

ggsave(
  filename = "plot_no_logo.png",
  path = here("2022", "2022-05-10"),
  dpi = 320,
  height = 20,
  width = 30,
  units = "cm"
  )
```

## Adding NY Times logo

```{r}
final_plot <- image_read("https://raw.githubusercontent.com/gafnts/tidy-tuesday/main/2022/2022-05-10/plot.png")

logo <- image_read("https://raw.githubusercontent.com/gafnts/tidy-tuesday/main/2022/2022-05-10/nyt_logo.png") %>% 
  image_resize(500)

final_plot %>% 
  image_composite(logo, offset = "+3200+0")
```
