```{r}
pacman::p_load(tidyverse, here, sysfonts, cowplot)
```

# Bee colonies

## (a) Import data

```{r}
colony <- 
  read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-01-11/colony.csv") %>% 
  mutate_if(is.numeric, ~replace(., is.na(.), 0))
```

## (b) Data wrangling

```{r}
colonies <- 
  colony %>%
  mutate(
    months = case_when(
      months == "January-March" ~ "",
      months == "April-June" ~ "Q2",
      months == "July-September" ~ "Q3",
      months == "October-December" ~ "Q4",
    ),
    year = paste0(year, "", months)
  ) %>%
  select(-months) %>%
  group_by(year) %>%
  summarise(
    colony_n = sum(colony_n),
    colony_lost = sum(colony_lost),
    colony_reno = sum(colony_reno)
  ) %>%
  ungroup() %>% 
  pivot_longer(-year)
```

## (c) Plot *à la* Financial Times

Reference: <https://www.instagram.com/p/CYWwHrSFtYD/>

```{r}
f1 <- "Nunito Sans Regular"
f2 <- "Nunito Sans Light"
```

```{r}
plot <- 
  colonies %>% 
  ggplot(aes(x = year, y = value, fill = name)) +
  geom_col() + 
  scale_y_continuous(label = scales::comma,
                     breaks = seq(0, 8e6, by = 1e6),
                     expand = c(0.0080, 0)) + 
  scale_x_discrete(breaks = c(2015, 2016, 2017, 2018, 2019, 2020, 2021), 
                   expand = c(0,0)) +
  theme(
        # X axis
        axis.title.x = element_blank(),
        axis.text.x = element_text(color = "#F2F2F2", size = 17, family = f2),
        axis.ticks.x = element_line(size = .5, color = "white"),
        axis.ticks.length.x = unit(0.25, "cm"),
        # Y axis
        axis.title.y = element_blank(),
        axis.text.y = element_text(color = "#F2F2F2", size = 17, family = f2),
        axis.ticks.y = element_blank(),
        # Grid
        panel.grid = element_line(color = "#F2F2F2", linetype = "dashed", size = .15),
        panel.grid.minor = element_blank(),
        panel.grid.major.x = element_blank(),
        # Legend
        legend.title = element_blank(),
        legend.text = element_text(size = 17, color = "gray", family = f2),
        legend.position = c(0.275, 1.1),
        legend.background = element_rect(fill = NA),
        legend.margin = margin(0, 0, 0, 0, "cm"),
        legend.key = element_rect(fill = NA),
        legend.key.size = unit(.65, "cm"),
        legend.direction = "horizontal",
        # Backgrounds
        plot.background = element_rect(fill = "#1D2026", color = NA),
        panel.background = element_rect(fill = "#1D2026"),
        # General margin
        plot.margin = margin(7.5, 2, 2.3, 2, "cm")) +
  scale_fill_manual(values = c("#A6325C", "#F272A1", "#62C3D9"),
                    labels = c("Colonies lost", "Number of colonies", "Colonies renovated")
  )

ggdraw(plot) +
  draw_label(
    "—",
    hjust = 0,
    x = .05,
    y = .96,
    size = 70,
    color = "#F2F2F2",
    fontfamily = f1
  ) +
  draw_label(
    "The number of bee colonies that are lost in the",
    hjust = 0,
    x = .05,
    y = .91,
    size = 28,
    color = "#F2F2F2",
    fontfamily = f1
  ) +
  draw_label(
    "US is greater than the number of those renewed",
    hjust = 0,
    x = .05,
    y = .865,
    size = 28,
    color = "#F2F2F2",
    fontfamily = f1
  ) +
  draw_label(
    "Total number of existing, lost and renovated colonies",
    hjust = 0,
    x = .05,
    y = .8,
    size = 17,
    color = "gray",
    fontfamily = f1
  ) +
  draw_label(
    "Source: United States Department of Agriculture",
    hjust = 0,
    x = .414,
    y = .05,
    size = 17,
    color = "gray",
    fontfamily = f1
  )
```

```{r}
ggsave(
  filename = "plot.png",
  path = here("2022", "(02) Bee colonies"),
  dpi = 320,
  height = 10,
  width = 10
)
```
